### ISSUE TITLE
code blocks with syntax highlights for email

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-fresh-emails#2]
can this pull that off? 😍

**Comment by DrShpongle** [comment]
we can try to play with something like this first: https://tohtml.com/jScript/

**Comment by vojtaholik** [comment]
https://github.com/eggheadio/egghead-fresh-emails/pull/3 needs some polish but works ;P

**Comment by vojtaholik** [comment]
#3  adds support for code blocks syntax highlighting
